# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script: Rscript -e 'write(x = paste("machine dataspace-staging.cavd.org login", Sys.getenv("DSR_login"), "password", Sys.getenv("DSR_pwd")), file = "~/.netrc")'

after_success:
  - Rscript -e 'covr::codecov()'
