# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
  - Rscript ci.R

after_success:
  - ./.trigger.sh
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
